kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-sc-standard-ns-default
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G

