---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: test
  name: jiva-sc-standard-ns-test
spec:
  storageClassName: openebs-jiva-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G
---
