---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: overprovisioning-disabled-sparse-pool
spec:
  name: overprovisioning-disabled-sparse-pool
  type: sparse
  maxPools: 1
  minPools: 1
  poolSpec:
    poolType: striped
    cacheFile: /var/openebs/pool1.cache
    thickProvisioning: true
